<?php

declare(strict_types=1);

/**
 * @file
 * Functions to support theming in the cepex theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function cepex_preprocess_html(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function cepex_preprocess_page(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function cepex_preprocess_node(array &$variables): void {

}

/**
 * Implémente hook_theme_suggestions_HOOK_alter() pour les vues en table.
 */
function cepex_theme_suggestions_views_view_table_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  $view_id = $view->id();
  $display_id = $view->current_display;

  // Ajoute une suggestion de template spécifique à la vue et à l'affichage.
  $suggestions[] = 'views_view_table__' . $view_id . '__' . $display_id;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function cepex_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']['#id'])) {
    $form_id = $variables['element']['#id'];
    
    // Ajouter une suggestion pour les formulaires de filtres exposés de vue
    if (strpos($form_id, 'views-exposed-form') !== FALSE) {
      // Récupérer le nom de la vue et de l'affichage
      $view_id = $variables['element']['#id'];
      $view_parts = explode('-', $view_id);
      
      if (isset($view_parts[3]) && isset($view_parts[4])) {
        $view_name = $view_parts[3];
        $display_id = $view_parts[4];
        
        // Ajouter des suggestions spécifiques pour cette vue
        $suggestions[] = 'form__views_exposed_form__' . $view_name;
        $suggestions[] = 'form__views_exposed_form__' . $view_name . '__' . $display_id;
        
        // Suggestion spécifique pour gestion-produit-par-exportateur-page-1
        if ($view_name == 'gestion_produit_par_exportateur' && $display_id == 'page_1') {
          $suggestions[] = 'form__views_exposed_form__gestion_produit_par_exportateur__page_1';
        }
      }
    }
  }
}
